config/routes.rb
Rails.application.routes.draw do
  namespace :crayta do
    get 'games' => "games#index", as: :games
    get 'games/:id' => "games#show", as: :game
    get 'games/:id/timeline' => "games#timeline", as: :game_timeline
    get 'games/:id/visits_history' => "games#visits_history", as: :game_visits_history
    get 'users/:id/games' => "users#games", as: :user_games
    get 'users' => "users#index"
  end
  resources :user_reactions
  resources :game_keys do
    member do
      patch :claim
    end
  end
  resources :afks, only: [:edit, :destroy, :new, :create]
  patch 'current_user/toggle_afk'
  get 'profile/edit'
  get 'profile/update'

  namespace :webhooks do
    get :twitch, to: "twitch#verify"
    post :twitch, to: "twitch#receive"
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/sessions', to: "sessions#destroy"

  root to: "landing#index"
end

app/models/afk.rb
# == Schema Information
#
# Table name: afks
#
#  id         :integer          not null, primary key
#  message    :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_afks_on_user_id  (user_id)
#

class Afk < ApplicationRecord
    belongs_to :user
end

app/controllers/afks_controller.rb
class AfksController < ApplicationController
  before_action :set_afk, only: %i[ show edit update destroy ]

  # GET /afks/new
  def new
    @afk = Afk.new
    @afk.user = current_user
  end

  # GET /afks/1/edit
  def edit
  end

  # POST /afks or /afks.json
  def create
    @afk = Afk.new(afk_params)
    @afk.user = current_user

    respond_to do |format|
      if @afk.save
        format.html { redirect_to edit_afk_url(@afk), notice: "Afk was successfully created." }
        format.json { render :show, status: :created, location: @afk }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @afk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /afks/1 or /afks/1.json
  def destroy
    if @afk == current_user.afk
      @afk.destroy
      respond_to do |format|
        format.html { redirect_to new_afk_url, notice: "Afk was successfully destroyed." }
        format.json { head :no_content }
      end
    else
      head 401
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_afk
      @afk = Afk.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def afk_params
      params.require(:afk).permit(:message)
    end
end

app/helpers/afk_helper.rb
module AfkHelper
  def afk_button_text(user)
    user.afk? ? "Return from AFK" : "Go AFK"
  end
  
  def afk_tippy_data(user)
    return unless user.afk?
    {
      controller: "tippy",
      "tippy-content": "You're already AFK"
    }
  end
end

app/helpers/afks_helper.rb
module AfksHelper
  def tippy_data
    return unless current_user.afk?
    {
      controller: "tippy",
      "tippy-content": "You're already AFK"
    }
  end

  def text
    if current_user.afk?
      "Return from AFK"
    else
      "Go AFK"
    end
  end
end

app/views/afks/_form.html.erb
<div class="p-3">
  <%- afk = afk.nil? ? current_user.build_afk : afk %>
  <%= turbo_frame_tag :afk do %>
    <%= form_with model: afk, method: afk.persisted? ? :delete : :post do |form| %>
      <%= form.label :comment, "Need to step away from the keyboard?", class: "block text-sm font-medium text-gray-700" %>
      <%= content_tag :div, class: "mt-1 flex rounded-md p-2 m-2", data: tippy_data do %>
        <%= form.text_field :message, disabled: current_user.afk?, class: "disabled:opacity-50 focus:ring-indigo-500 focus:border-indigo-500 flex-1 block w-full rounded-md sm:text-sm border-gray-300", placeholder: "I'm late for a very important date"  %>
      <% end %>
      <%= render 'shared/button' do %>
        <%= text %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/afks/edit.html.erb
<h1>Editing Afk</h1>

<%= render 'form', afk: @afk %>

<%= link_to 'Show', @afk %> |
<%= link_to 'Back', afks_path %>

app/views/afks/new.html.erb
<h1>New Afk</h1>

<%= render 'form', afk: @afk %>

<%= link_to 'Back', afks_path %>