config/routes.rb
Rails.application.routes.draw do
  namespace :crayta do
    get 'games' => "games#index", as: :games
    get 'games/:id' => "games#show", as: :game
    get 'games/:id/timeline' => "games#timeline", as: :game_timeline
    get 'games/:id/visits_history' => "games#visits_history", as: :game_visits_history
    get 'users/:id/games' => "users#games", as: :user_games
    get 'users' => "users#index"
  end
  resources :user_reactions
  resources :game_keys do
    member do
      patch :claim
    end
  end
  resources :afks, only: [:edit, :destroy, :new, :create]
  patch 'current_user/toggle_afk'
  get 'profile/edit'
  get 'profile/update'

  namespace :webhooks do
    get :twitch, to: "twitch#verify"
    post :twitch, to: "twitch#receive"
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/sessions', to: "sessions#destroy"

  root to: "landing#index"
end

app/models/game_key.rb
# == Schema Information
#
# Table name: game_keys
#
#  id         :bigint           not null, primary key
#  claimed    :boolean          default(FALSE)
#  key        :string
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class GameKey < ApplicationRecord
  has_many :game_key_servers, dependent: :destroy
  has_many :servers, through: :game_key_servers

  scope :unclaimed, -> { where(claimed: false) }
  scope :claimed, -> { where(claimed: true) }

  validates_presence_of :name
  validates_presence_of :key
  validates_presence_of :servers

  def claim!
    update(claimed: true)
  end
end

app/controllers/game_keys_controller.rb
class GameKeysController < ApplicationController
  before_action :protect
  before_action :set_game_key, only: %i[ show edit update destroy ]
  before_action :validate_owner, only: %i[edit update destroy]

  # GET /game_keys or /game_keys.json
  def index
    @pagy, @game_keys = pagy(GameKey.eager_load(:servers).where(claimed: false, servers: current_user.servers).order(created_at: :desc))
  end

  # GET /game_keys/1 or /game_keys/1.json
  def show
  end

  # GET /game_keys/new
  def new
    @game_key = GameKey.new
    session[:model] = @game_key unless @stimulus_reflex
  end

  # GET /game_keys/1/edit
  def edit
  end

  # POST /game_keys or /game_keys.json
  def create
    @game_key = GameKey.new(game_key_params)

    respond_to do |format|
      if @game_key.save
        format.html { redirect_to game_keys_url, notice: "Game key was successfully created." }
        format.json { render :show, status: :created, location: @game_key }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game_key.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /game_keys/1 or /game_keys/1.json
  def update
    respond_to do |format|
      if @game_key.update(game_key_params)
        format.html { redirect_to @game_key, notice: "Game key was successfully updated." }
        format.json { render :show, status: :ok, location: @game_key }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game_key.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH /game_keys/:id/claim
  def claim
    @game_key = GameKey.unclaimed
                       .joins(:servers)
                       .where(servers: { id: current_user.servers.select(:id) })
                       .find_by(id: params[:id])

    return head :not_found unless @game_key

    @game_key.claim!

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to game_keys_path, notice: t("game_keys.claimed", default: "Game key claimed!") }
    end
  end

  # DELETE /game_keys/1 or /game_keys/1.json
  def destroy
    @game_key.destroy
    respond_to do |format|
      format.html { redirect_to game_keys_url, notice: "Game key was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_game_key
    @game_key = GameKey.find(params[:id])
    session[:model] = @game_key unless @stimulus_reflex
  end

  # Only allow a list of trusted parameters through.
  def game_key_params
    params.require(:game_key).permit(:key, :name, server_ids: [])
  end

  # todo: actually add the creator to these, and check it
  def validate_owner
    redirect_back(fallback_location: root_url)
  end
end

app/helpers/game_keys_helper.rb
module GameKeysHelper
end

app/views/game_keys/_form.html.erb
<%= render 'shared/paper' do %>
  <div class="p-3">
    <%= form_with(model: game_key, builder: CustomFormBuilder) do |form| %>
      <% if game_key.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(game_key.errors.count, "error") %> prohibited this game_key from being saved:</h2>

          <ul>
            <% game_key.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= form.container_for :name do %>
        <%= form.label :name %>
        <%= form.text_field :name %>
        <%= form.error_for :name %>
      <% end %>

      <%= form.container_for :key do %>
        <%= form.label :key %>
        <%= form.text_field :key %>
        <%= form.error_for :key %>
      <% end %>

      <%= form.container_for :server_ids do %>
        <%= form.label :server_ids, t(".servers") %>
        <%= form.select :server_ids, options_from_collection_for_select(current_user.servers, :id, :name), {}, { multiple: true } %>
        <%= form.error_for :server_ids %>
      <% end %>

      <div class="actions">
        <%= render 'shared/button', type: 'submit' do %>
          <%= t(".submit") %>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/game_keys/_game_key.html.erb
<div id="<%= dom_id(game_key) %>">
  <%= render 'shared/paper' do %>
    <div class="p-3">
      <div class="grid grid-cols-2 gap-2 h-24">
        <div class="w-full bg-gray-400 rounded-lg"></div>
        <div class="flex flex-col items-start ml-4">
          <h4 class="text-xl font-semibold"><%= game_key.name %></h4>
          <% if key_visible %>
            <p class="text-sm"><%= game_key.key %></p>
          <% else %>
            <%= form_with url: claim_game_key_path(game_key), method: :patch, data: { turbo_confirm: t(".confirm-claim") } do %>
              <%= hidden_field_tag :view, 'card' %>
              <%= render 'shared/button', type: 'submit' do %>
                <%= t(".claim") %>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/game_keys/_game_key_row.html.erb
<tr id="<%= dom_id(game_key) %>">
  <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6"><%= game_key.name %></td>
  <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= game_key.servers.first.name %></td>
  <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
    <% if key_visible %>
      <span class="whitespace-nowrap px-3 py-4 text-sm"><%= game_key.key %></span>
    <% else %>
      <%= button_to t(".claim"), claim_game_key_path(game_key), method: :patch,
            params: { view: "row" },
            form: { data: { turbo_confirm: t(".confirm-claim") } },
            class: "text-indigo-600 hover:text-indigo-900" %>
    <% end %>
  </td>
</tr>

app/views/game_keys/claim.turbo_stream.erb
<% if params[:view] == 'row' %>
  <%= turbo_stream.replace dom_id(@game_key) do %>
    <%= render partial: "game_keys/game_key_row", locals: { game_key: @game_key, key_visible: true } %>
  <% end %>
<% else %>
  <%= turbo_stream.replace dom_id(@game_key) do %>
    <%= render partial: "game_keys/game_key", locals: { game_key: @game_key, key_visible: true } %>
  <% end %>
<% end %>

app/views/game_keys/edit.html.erb
<h1>Editing Game Key</h1>

<%= render 'form', game_key: @game_key %>

<%= link_to 'Show', @game_key %> |
<%= link_to 'Back', game_keys_path %>

app/views/game_keys/index.html.erb
<% content_for(:title) { t(".game_keys") } %>


<div class="px-4 sm:px-6 lg:px-8">
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto"></div>
    <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
      <%= link_to 'New Game Key', new_game_key_path, class: "inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 sm:w-auto" %>
    </div>
  </div>
  <div class="mt-8 flex flex-col">
    <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
        <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">
          <table class="min-w-full divide-y divide-gray-300">
            <thead class="bg-gray-50">
              <tr>
                <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Game Name</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Server</th>
                <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                  <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Key</th>
                </th>
              </tr>
            </thead>
            <tbody class="divide-y divide-gray-200 bg-white">
              <%= render partial: "game_keys/game_key_row", as: :game_key, collection: @game_keys, locals: { key_visible: false } %>
            </tbody>
          </table>
        </div>
        <div class="mt-4">
          <%== pagy_nav(@pagy) %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/game_keys/new.html.erb
<h1>New Game Key</h1>

<%= render 'form', game_key: @game_key %>

<%= link_to 'Back', game_keys_path %>

app/views/game_keys/show.html.erb
<p id="notice"><%= notice %></p>

<% content_for(:title) { t(".game_key") } %>

<%= render 'shared/paper' do %>
  <div class="p-3">
    <%= styled_label_for @game_key, :name %>
    <%= @game_key.name %>
  </div>

  <div class="p-3">
    <%= styled_label_for @game_key, :key %>
    <%= @game_key.name %>
  </div>

  <div class="p-3">
    <%= styled_label_for @game_key, :servers %>
    <% @game_key.servers.each do |server| %>
      <%= server.name %>
    <% end %>
  </div>
<% end %>


<%= link_to 'Edit', edit_game_key_path(@game_key) %> |
<%= link_to 'Back', game_keys_path %>