config/routes.rb
Rails.application.routes.draw do
  namespace :crayta do
    get 'games' => "games#index", as: :games
    get 'games/:id' => "games#show", as: :game
    get 'games/:id/timeline' => "games#timeline", as: :game_timeline
    get 'games/:id/visits_history' => "games#visits_history", as: :game_visits_history
    get 'users/:id/games' => "users#games", as: :user_games
    get 'users' => "users#index"
  end
  resources :user_reactions
  resources :game_keys do
    member do
      patch :claim
    end
  end
  resources :afks, only: [:edit, :destroy, :new, :create]
  patch 'current_user/toggle_afk'
  get 'profile/edit'
  get 'profile/update'

  namespace :webhooks do
    get :twitch, to: "twitch#verify"
    post :twitch, to: "twitch#receive"
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/sessions', to: "sessions#destroy"

  root to: "landing#index"
end

app/controllers/crayta/games_controller.rb
class Crayta::GamesController < ApplicationController
  before_action :set_game, only: [:show, :timeline, :visits_history]

  def index
    query = CraytaGame.order(visits: :desc)
    if params[:q]
      query = query.where(CraytaGame.arel_table[:name].matches("%#{params[:q]}%"))
    end
    @pagy, @games = pagy(query)
  end

  def show
  end

  def timeline
    render json: @game.times_in_rails
  end

  def visits_history
    data = @game.versions.group_by_day(&:created_at).transform_values do |value|
      value.map { |a| a&.reify&.visits }.compact
    end
    render json: data
  end

  private
  def set_game
    @game = CraytaGame.find(params[:id])
  end
end

app/controllers/crayta/users_controller.rb
class Crayta::UsersController < ApplicationController
  before_action :set_user, only: [:games]

  def index
    query = CraytaUser.order(crayta_games_count: :desc)
    if params[:q] 
      query = query.where(CraytaUser.arel_table[:name].matches("%#{params[:q]}%"))
    end
    @pagy, @users = pagy(query)
  end
  
  def games
    @pagy, @games = pagy(@user.crayta_games.order(visits: :desc))
  end

  private

  def set_user
    @user = CraytaUser.find(params[:id])
  end
end

app/helpers/crayta/games_helper.rb
module Crayta::GamesHelper
end

app/helpers/crayta/users_helper.rb
module Crayta::UsersHelper
end

app/views/crayta/games/_table.html.erb
<%= render 'shared/table', headers: [t(".name"), t(".creator"), t(".visits"), ''] do %>
  <% games.each do |game| %>
    <tr>
      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900"><%= game.name %></td>
      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900"><%= link_to game.crayta_user.name, crayta_user_games_url(game.crayta_user) %></td>
      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900"><%= game.visits.to_s %></td>
      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900"><%= link_to('Show', game) %></td>
    </tr>
  <% end %>
<% end %>

<%== pagy_nav(pagy) %>

app/views/crayta/games/index.html.erb
<% content_for(:subnav) do %>
  <%= render 'shared/crayta_sub_nav' %>
<% end %>

<%= render 'shared/searchbar' %>

<div>
  <span class="font-bold"><%= t(".total_visits") %></span>
  <span><%= number_to_human CraytaGame.sum(:visits) %></span>
</div>

<div>
  <span class="font-bold"><%= t(".total_games") %></span>
  <span><%= number_to_human CraytaGame.count %></span>
</div>

<%= render "crayta/games/table", pagy: @pagy, games: @games %>

app/views/crayta/games/search.html.erb
<h1>Crayta::Games#search</h1>
<p>Find me in app/views/crayta/games/search.html.erb</p>

app/views/crayta/games/show.html.erb
<%= content_for(:subnav) { render 'shared/crayta_sub_nav' } %>

<div class="space-y-4">
  <div class="grid grid-flow-col grid-cols-3 gap-4">
    <div>
      <%= image_tag @game.cover_url %>
    </div>
    <div class="col-span-2">
      <%= render 'shared/data_list',
          header: @game.name,
          subtitle: "",
          data: [
              [t(".total_visits"), @game.visits],
              [t(".rank"), @game.rank],
              [t(".play"), link_to(t(".play_link"), @game.external_url)],
          ] %>
    </div>
  </div>

<h2 class="text-lg font-bold"><%= t(".time_spent") %></h2>
  <%= timeline crayta_game_timeline_url(@game) %>
  <%= area_chart crayta_game_visits_history_url(@game) %>
</div>