config/routes.rb
Rails.application.routes.draw do
  namespace :crayta do
    get 'games' => "games#index", as: :games
    get 'games/:id' => "games#show", as: :game
    get 'games/:id/timeline' => "games#timeline", as: :game_timeline
    get 'games/:id/visits_history' => "games#visits_history", as: :game_visits_history
    get 'users/:id/games' => "users#games", as: :user_games
    get 'users' => "users#index"
  end
  resources :user_reactions
  resources :game_keys do
    member do
      patch :claim
    end
  end
  resources :afks, only: [:edit, :destroy, :new, :create]
  patch 'current_user/toggle_afk'
  get 'profile/edit'
  get 'profile/update'

  namespace :webhooks do
    get :twitch, to: "twitch#verify"
    post :twitch, to: "twitch#receive"
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/sessions', to: "sessions#destroy"

  root to: "landing#index"
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :bigint           not null, primary key
#  avatar_url :string
#  banned     :boolean          default(FALSE)
#  email      :string
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class User < ApplicationRecord
  has_one :afk
  has_many :birthdays
  has_many :so_chat_cookies

  has_many :launch_alerts
  has_many :launch_alert_configs, through: :launch_alerts

  has_many :user_servers
  has_many :servers, through: :user_servers

  def self.login(auth_hash)
    user = User.where(id: auth_hash.uid).first_or_create
    user.sync_servers!(token: auth_hash["credentials"]["token"])
    user.update(
      name: auth_hash["info"].name,
      email: auth_hash["info"].email,
      avatar_url: auth_hash["info"].image
    )
    user
  end

  def sync_servers!(token:)
    response = Discordrb::API::User.servers("Bearer #{token}")
    json = JSON.parse(response.body)
    json.each do |record|
      server = Server.where(external_id: record["id"]).first_or_initialize
      server.assign_attributes(
        name: record["name"],
        icon: record["icon"]
      )
      server.save
      UserServer.where(server: server, user: self).first_or_create(owner: record["owner"])
    end
  end

  def afk?
    afk.present? && afk.persisted?
  end

  def afk!(message = "I'll be back")
    update(afk: Afk.create(message: message))
  end

  def back!
    afk.destroy if afk?
  end
end

app/controllers/user_reactions_controller.rb
class UserReactionsController < ApplicationController
  before_action :protect
  before_action :set_user_reaction, only: %i[ show edit update destroy ]
  before_action :validate_owner, only: %i[edit update destroy]

  # GET /user_reactions or /user_reactions.json
  def index
    @pagy, @user_reactions = pagy(UserReaction.all)
  end

  # GET /user_reactions/1 or /user_reactions/1.json
  def show
  end

  # GET /user_reactions/new
  def new
    @user_reaction = UserReaction.new
    session[:model] = @user_reaction unless @stimulus_reflex
  end

  # GET /user_reactions/1/edit
  def edit
  end

  # POST /user_reactions or /user_reactions.json
  def create
    @user_reaction = UserReaction.new(user_reaction_params)

    respond_to do |format|
      if @user_reaction.save
        format.html { redirect_to @user_reaction, notice: "User reaction was successfully created." }
        format.json { render :show, status: :created, location: @user_reaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_reaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_reactions/1 or /user_reactions/1.json
  def update
    respond_to do |format|
      if @user_reaction.update(user_reaction_params)
        format.html { redirect_to @user_reaction, notice: "User reaction was successfully updated." }
        format.json { render :show, status: :ok, location: @user_reaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_reaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_reactions/1 or /user_reactions/1.json
  def destroy
    @user_reaction.destroy
    respond_to do |format|
      format.html { redirect_to user_reactions_url, notice: "User reaction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_reaction
      @user_reaction = UserReaction.find(params[:id])
      session[:model] = @user_reaction unless @stimulus_reflex
    end

    # Only allow a list of trusted parameters through.
    def user_reaction_params
      params.require(:user_reaction).permit(:regex, :output, server_ids: [])
    end

  def validate_owner
    redirect_back(fallback_location: root_url) unless current_user == @user_reaction.user
  end
end

app/helpers/user_reactions_helper.rb
module UserReactionsHelper
end

app/views/user_reactions/_form.html.erb
<div class="grid grid-cols-1 gap-2 xl:max-w-6xl max-w-4xl" data-controller="reaction-tester">
  <%= render 'shared/paper' do %>
    <div class="p-3">
      <%= form_with(model: user_reaction, builder: CustomFormBuilder) do |form| %>

        <%= form.container_for :regex do %>
          <%= form.label :regex %>
          <%= form.text_field :regex, data: { "reaction-tester-target": "regex" } %>
          <%= form.error_for :regex %>
        <% end %>

        <%= form.container_for :output do %>
          <%= form.label :output %>
          <%= form.text_field :output, data: { "reaction-tester-target": "output" } %>
          <%= form.error_for :output %>
        <% end %>

        <%= form.container_for :chance do %>
          <%= form.label :chance %>
          <%= form.text_field :chance, type: "number", max: 1, min: 0, step: 0.01, data: { "reaction-tester-target": "output" } %>
          <%= form.error_for :chance %>
        <% end %>

        <%= form.container_for :server_ids do %>
          <%= form.label :server_ids, t('.servers') %>
          <%= form.select :server_ids, options_from_collection_for_select(current_user.servers, :id, :name, form.object.server_ids), {}, { multiple: true } %>
          <%= form.error_for :server_ids %>
        <% end %>

        <div class="actions">
          <%= render 'shared/button' do %>
            <%= t(".submit") %>
          <% end %>
        </div>
      <% end %>

    </div>
  <% end %>

  <%= render 'shared/paper' do %>
    <div class="p-3">
      <h6><%= t(".user-reaction-test-title") %></h6>
      <%= styled_label_for :user_reaction, :input %>
      <%= styled_text_field :user_reaction, :input, data: { "reaction-tester-target": "input" } %>

      <%= render "user_reactions/test_result", output: "" %>

      <div class="mt-3">
        <%= render 'shared/button', data: {action: "click->reaction-tester#run"} do %>
          <%= t(".test") %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/user_reactions/_test_result.html.erb
<div id="test-result">
  <%= styled_label_for :user_reaction, :test_output %>
  <%= styled_text_field :user_reaction, :test_output, value: output %>

  <div class="text-sm pt-3 pl-1">
    <% if local_assigns.key?(:match) %>
      <% if match %>
        <span class="text-green-500"><%= t(".match") %></span>
      <% else %>
        <span class="text-red-500"><%= t(".no-match") %></span>
      <% end %>
    <% end %>
  </div>
</div>

app/views/user_reactions/edit.html.erb
<% content_for(:title) { t(".title")} %>

<%= render 'form', user_reaction: @user_reaction %>

<%= link_to 'Show', @user_reaction %> |
<%= link_to 'Back', user_reactions_path %>

app/views/user_reactions/index.html.erb
<p id="notice"><%= notice %></p>

<% content_for(:title) { t(".title")} %>

<%= render 'shared/table', headers: [t(".regex"), t(".output"), ''] do %>
  <% @user_reactions.each do |user_reaction| %>
    <tr>
      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900"><%= user_reaction.regex %></td>
      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900 text-ellipsis overflow-hidden"><%= user_reaction.output %></td>
      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900 w-64">
        <%= link_to 'Show', user_reaction %>
        <%= link_to 'Edit', edit_user_reaction_path(user_reaction) if current_user == user_reaction.user %>
        <%= link_to 'Destroy', user_reaction, method: :delete, data: {confirm: 'Are you sure?'} if current_user == user_reaction.user %>
      </td>
    </tr>
  <% end %>
<% end %>

<%== pagy_nav(@pagy) %>

<br>

<%= link_to 'New User Reaction', new_user_reaction_path %>

app/views/user_reactions/new.html.erb
<% content_for(:title) { t(".title")} %>

<%= render 'form', user_reaction: @user_reaction %>

<%= link_to 'Back', user_reactions_path %>

app/views/user_reactions/show.html.erb
<% content_for(:title) { t(".title") } %>

<%= render 'shared/paper' do %>
  <div class="p-3">
    <div class="p-3">
      <%= styled_label_for :user_reaction, :regex %>
      <pre><%= @user_reaction.regex %></pre>
    </div>

    <div class="p-3">
      <%= styled_label_for :user_reaction, :output %>
      <pre class="whitespace-pre-wrap"><%= @user_reaction.output %></pre>
    </div>
  </div>
<% end %>

<% if current_user == @user_reaction.user %>
  <%= link_to 'Edit', edit_user_reaction_path(@user_reaction) %> |
<% end %>
<%= link_to 'Back', user_reactions_path %>